### ISSUE TITLE
Incompatible with Hogfather

### ISSUE THREAD

**Issue by yuu1412** [dryoo/livemark#3]
sorry i cannot provide good amount of data. 

Livemark does not provide watermarking on Hogfather

- ver: hogfather
- browser: chrome (latest on PC and android), latest built in ver of samsung browser

**Comment by dryoo** [comment]
sorry for late, but I will test soon...

**Comment by dryoo** [comment]
I think this works with hogfather.
Did you installed php-gd library on your server? Check it!


http://vaslor.net:51010/doku.php?id=start
